web/old_web/models.py
import dns.resolver
from datetime import datetime
from app import db

class AutonomousSystem(db.Model):
    asn = db.Column(db.Integer, primary_key=True, index=True)
    name = db.Column(db.String(100))
    created_timestamp = db.Column(db.DateTime, default=datetime.now)
    modified_timestamp = db.Column(db.DateTime, default=datetime.now, onupdate=datetime.now)
    origin_prefixes = db.relationship('Prefix', backref='autonomous_system', lazy='joined')
    #best_route_prefixes = db.relationship('Prefix', backref='autonomous_system', lazy='joined')


    def __init__(self, *args, **kwargs):
        super(AutonomousSystem, self).__init__(*args, **kwargs)
        # self.asn  = int(asn)
        # self.name = self._asn_name_query(asn)

    def __repr__(self):
        return '<ASN: %s>' % self.asn

    # @property
    # def asn(self):
    #     return self._asn
    #
    # @asn.setter
    # def asn(self, asn):
    #     if int(asn):
    #         self._asn = asn
    #     else:
    #         raise ValueError('ASN should be a positive number')
    #
    # def _asn_name_query(self, asn):
    #      query = 'AS' + str(asn) + '.asn.cymru.com'
    #      answers = dns.resolver.query(query, 'TXT')
    #      for rdata in answers:
    #          for txt_string in rdata.strings:
    #              return txt_string.split('|')[-1].split(",", 2)[0].strip()


class Prefix(db.Model):
    id = db.Column(db.Integer, primary_key=True, index=True)
    status = db.Column(db.String(64))
    prefix = db.Column(db.String(128), unique=True)
    next_hop_ip = db.Column(db.String(64))
    metric = db.Column(db.Integer)
    local_pref = db.Column(db.Integer)
    weight = db.Column(db.Integer)
    as_path = db.Column(db.Text)
    route_origin = db.Column(db.String(64))
    origin_asn = db.Column(db.Integer)
    next_hop_asn  = db.Column(db.Integer, db.ForeignKey('autonomous_system.asn'))
    created_timestamp  = db.Column(db.DateTime, default=datetime.now)
    modified_timestamp = db.Column(db.DateTime, default=datetime.now, onupdate=datetime.now)
    # autonomoussystem_asn = db.Column(db.Integer, db.ForeignKey('autonomous_system.asn'))
    ip_version = db.Column(db.Integer)

    def __init__(self, *args, **kwargs):
        super(Prefix, self).__init__(*args, **kwargs)

    def __repr__(self):
        return '<Prefix: %s>' % self.prefix

    def __str__(self):
        return str(self.__dict__)

    #
    # def _valid_as_path(self, as_path):
    #     # as_path must be empty or a tuple of integers
    #     if (list(as_path) or not as_path):
    #         return True
    #     else:
    #         return False
    #
    # @property
    # def as_path(self):
    #     return self._as_path
    #
    # @as_path.setter
    # def as_path(self, as_path):
    #     if self._valid_as_path(as_path):
    #         self._as_path = as_path
    #     else:
    #         raise ValueError('Invalid AS Path')

web/old_web/app.py
from flask import Flask
from flask.ext.migrate import Migrate, MigrateCommand
from flask.ext.script import Manager
from flask.ext.sqlalchemy import SQLAlchemy
from sqlalchemy import func, distinct

from config import Configuration  # import our configuration data.

app = Flask(__name__)
app.config.from_object(Configuration)  # use values from our Configuration object.
db = SQLAlchemy(app)
migrate = Migrate(app, db)

manager = Manager(app)
manager.add_command('db', MigrateCommand)

web/old_web/asn/blueprint.py
from flask import Blueprint
from helpers import object_list
from models import AutonomousSystem, Prefix

asn = Blueprint('asn', __name__, template_folder='templates')

@asn.route('/')
def index():
    asn = AutonomousSystem.query.order_by(AutonomousSystem.asn.asc())
    # autonomoussystems = db.session.query(AutonomousSystem)
    return object_list('asn/index.html', asn)

web/old_web/main.py
from app import app, db
import models
import views

from asn.blueprint import asn
app.register_blueprint(asn, url_prefix='/asn')

if __name__ == '__main__':
    app.run()

web/old_web/views.py
from flask import render_template
from app import app
from app import db
from models import AutonomousSystem, Prefix
from sqlalchemy import func, distinct
from helpers import object_list

@app.route('/')
def homepage():
    autonomoussystems = db.session.query(AutonomousSystem.asn, AutonomousSystem.name)
    prefixes = db.session.query(Prefix.ip_version)
    ipv4_prefixes = prefixes.filter(Prefix.ip_version == 4)
    ipv6_prefixes = prefixes.filter(Prefix.ip_version == 6)
    nexthop_asns = db.session.query(Prefix.next_hop_asn.distinct())
    nexthop_ips  = db.session.query(Prefix.next_hop_ip.distinct())
    peers = autonomoussystems.filter(AutonomousSystem.asn.in_(nexthop_asns))

    return render_template('home.html',
                            autonomoussystems=autonomoussystems,
                            prefixes=prefixes,
                            ipv4_prefixes=ipv4_prefixes,
                            ipv6_prefixes=ipv6_prefixes,
                            nexthop_ips=nexthop_ips,
                            peers=peers)

web/old_web/asn/templates/asn/index.html
{% extends "layout.html" %}
{% block title %}Autonomous Systems{% endblock %}
{% block content_title %}Autonomous Systems{% endblock %}

{% block content %}
  {% include "includes/list.html" %}
  {% include "includes/page_links.html" %}
{% endblock %}

web/old_web/asn/templates/includes/list.html
<div class="col-md-12 col-sm-12 col-xs-12">
    <div class="x_panel">
        <div class="x_title">
            <h2>All Autonomous Systems</h2>
            <div class="clearfix"></div>
        </div>
        <div class="x_content">
            <table id="example" class="table table-striped responsive-utilities jambo_table">
                <thead>
                    <tr class="headings">
                        <th>
                            <input type="checkbox" class="tableflat">
                        </th>
                        <th>ASN </th>
                        <th>Name </th>
                        <th>Description </th>
                        <th>Routes Orginated </th>
                        <th>Updated </th>
                        <th class=" no-link last"><span class="nobr">Action</span>
                        </th>
                    </tr>
                </thead>
  <tbody>
{% for asn in object_list.items %}
  <!-- <p><a href="{{ url_for('asn.index') }}">{{ asn.asn }}</a>{{asn.name}}</p> -->
  <tr>
    <td class="a-center ">
        <input type="checkbox" class="tableflat">
    </td>
    <td><a href="http://bgp.he.net/AS{{asn.asn}}">{{asn.asn}}</a></td>
    {% if asn.name.split(' -', 1)[1] %}
      <td>{{asn.name.split(' -', 1)[1]}}</td>
      <td>{{asn.name.split(' -', 1)[0]}}</td>
    {% else %}
      <td>{{asn.name.split(' ', 1)[1]}}</td>
      <td>{{asn.name.split(' ', 1)[0]}}</td>
    {% endif %}
    <td>{{asn.prefixes|length}}</td>
    <td>{{asn.modified_timestamp.strftime("%Y-%m-%d %H:%M:%S %Z")}}</td>
    <td class=" last"><a href="#">View</a>
  </tr>
{% endfor %}
</tbody>
</table>

web/old_web/templates/home.html
{% extends "layout.html" %}
{% block title %}Autonomous Systems{% endblock %}
{% block content_title %}NERO BGP Dashboard{% endblock %}

{% block content %}
<!-- page content -->
<div class="right_col" role="main">

    <!-- top tiles -->
    <div class="row tile_count">
        <div class="animated flipInY col-md-2 col-sm-4 col-xs-4 tile_stats_count">
            <div class="left"></div>
            <div class="right">
                <span class="count_top">Autonomous Systems</span>
                <div class="count">{{ '{0:,}'.format(autonomoussystems.count()) }}</div>
                <span class="count_bottom"><i class="green"><i class="fa fa-sort-asc"></i>4 </i> Since last update</span>
            </div>
        </div>
        <div class="animated flipInY col-md-2 col-sm-4 col-xs-4 tile_stats_count">
            <div class="left"></div>
            <div class="right">
                <span class="count_top">IPv4 Prefixes</span>
                <div class="count">{{ '{0:,}'.format(ipv4_prefixes.count()) }} </div>
                <span class="count_bottom"><i class="green"><i class="fa fa-sort-asc"></i>3 </i> Since last update</span>
            </div>
        </div>
        <div class="animated flipInY col-md-2 col-sm-4 col-xs-4 tile_stats_count">
            <div class="left"></div>
            <div class="right">
              <span class="count_top">IPv6 Prefixes</span>
              <div class="count">{{ '{0:,}'.format(ipv6_prefixes.count()) }} </div>
                <span class="count_bottom"><i class="green"><i class="fa fa-sort-asc"></i>34 </i> Since last update</span>
            </div>
        </div>
        <div class="animated flipInY col-md-2 col-sm-4 col-xs-4 tile_stats_count">
            <div class="left"></div>
            <div class="right">
              <span class="count_top">BGP Peers</span>
              <div class="count">{{ '{0:,}'.format(peers.count()) }} </div>
                <span class="count_bottom"><i class="red"><i class="fa fa-sort-desc"></i>12 </i> Since last update</span>
            </div>
        </div>
        <div class="animated flipInY col-md-2 col-sm-4 col-xs-4 tile_stats_count">
            <div class="left"></div>
            <div class="right">
              <span class="count_top">Egress Connections</span>
              <div class="count">{{ '{0:,}'.format(nexthop_ips.count()) }} </div>
                <span class="count_bottom"><i class="green"><i class="fa fa-sort-asc"></i>34 </i> Since last update</span>
            </div>
        </div>
        <div class="animated flipInY col-md-2 col-sm-4 col-xs-4 tile_stats_count">
            <div class="left"></div>
            <div class="right">
                <span class="count_top">Last Update</span>
                <div class="count">Today</div>
            </div>
        </div>

    </div>
    <!-- /top tiles -->

        <div class="clearfix"></div>

        <div class="row">

            <div class="col-md-12 col-sm-12 col-xs-12">
                <div class="x_panel">
                    <div class="x_title">
                        <h2>BGP Peers <small>Sessions</small></h2>
                        <ul class="nav navbar-right panel_toolbox">
                            <li><a href="#"><i class="fa fa-chevron-up"></i></a>
                            </li>
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-wrench"></i></a>
                                <ul class="dropdown-menu" role="menu">
                                    <li><a href="#">Settings 1</a>
                                    </li>
                                    <li><a href="#">Settings 2</a>
                                    </li>
                                </ul>
                            </li>
                            <li><a href="#"><i class="fa fa-close"></i></a>
                            </li>
                        </ul>
                        <div class="clearfix"></div>
                    </div>
                    <div class="x_content">
                        <table id="example" class="table table-striped responsive-utilities jambo_table">
                            <thead>
                                <tr class="headings">
                                    <th>
                                        <input type="checkbox" class="tableflat">
                                    </th>
                                    <th>ASN </th>
                                    <th>Name </th>
                                    <th>Description </th>
                                    <th>Updated </th>
                                    <th class=" no-link last"><span class="nobr">Action</span>
                                    </th>
                                </tr>
                            </thead>

                            <tbody>
                              {% for asn in peers %}
                                <!-- <p><a href="{{ url_for('asn.index') }}">{{ asn.asn }}</a>{{asn.name}}</p> -->
                                <tr>
                                  <td class="a-center ">
                                      <input type="checkbox" class="tableflat">
                                  </td>
                                  <td><a href="http://bgp.he.net/AS{{asn.asn}}">{{asn.asn}}</a></td>
                                  {% if asn.name.split(' -', 1)[1] %}
                                    <td>{{asn.name.split(' -', 1)[1]}}</td>
                                    <td>{{asn.name.split(' -', 1)[0]}}</td>
                                  {% else %}
                                    <td>{{asn.name.split(' ', 1)[1]}}</td>
                                    <td>{{asn.name.split(' ', 1)[0]}}</td>
                                  {% endif %}
                                  <td>2015-12-31 12:49:36</td>
                                  <td class=" last"><a href="#">View</a>
                                </tr>
                              {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>

            <br />
            <br />
            <br />

        </div>
    </div>

    <!-- footer content -->

    <!-- /footer content -->
</div>
<!-- /page content -->
{% endblock %}

web/old_web/templates/includes/page_links.html
<ul class="pagination">
  <li{% if not object_list.has_prev %} class="disabled"{% endif %}>
    {% if not object_list.has_prev %}
      <a href="./?page={{ object_list.prev_num }}">&laquo;</a>
    {% else %}
      <a href="#">&laquo;</a>
    {% endif %}
  </li>
  {% for page in object_list.iter_pages() %}
    <li>
      {% if page %}
        <a {% if page == object_list.page %}class="active" {% endif %}href="./?page={{ page }}">{{ page }}</a>
      {% else %}
        <a class="disabled">...</a>
      {% endif %}
    </li>
  {% endfor %}
  <li{% if not object_list.has_next %} class="disabled"{% endif %}>
    {% if object_list.has_next %}
      <a href="./?page={{ object_list.next_num }}">&raquo;</a>
    {% else %}
      <a href="#">&raquo;</a>
    {% endif %}
  </li>
</ul>

web/old_web/templates/layout.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
  <!-- Meta, title, CSS, favicons, etc. -->
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <title>{% block title %}{% endblock %} | BGP Dashboard</title>

  <!-- Bootstrap core CSS -->

  <link href="/static/css/bootstrap.min.css" rel="stylesheet">

  <link href="/static/fonts/css/font-awesome.min.css" rel="stylesheet">
  <link href="/static/css/animate.min.css" rel="stylesheet">

  <!-- Custom styling plus plugins -->
  <link href="/static/css/custom.css" rel="stylesheet">
  <link rel="stylesheet" type="text/css" href="/static/css/maps/jquery-jvectormap-2.0.1.css" />
  <link href="/static/css/icheck/flat/green.css" rel="stylesheet" />
  <link href="/static/css/floatexamples.css" rel="stylesheet" type="text/css" />

  <script src="/static/js/jquery.min.js"></script>
  <script src="/static/js/nprogress.js"></script>
  <script>
    NProgress.start();
  </script>

  <!--[if lt IE 9]>
        <script src="../assets/js/ie8-responsive-file-warning.js"></script>
        <![endif]-->

  <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
  <!--[if lt IE 9]>
          <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
          <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
        <![endif]-->

</head>

<body class="nav-sm">
  <div class="container body">
    <div class="main_container">
      <!-- top navigation -->
      <div class="top_nav">
        <div class="nav_menu">
          <nav class="" role="navigation">
          </nav>
          <ul class="nav navbar-nav navbar-right">
            <div class="title_right">
              <div class="col-md-5 col-sm-5 col-xs-12 form-group pull-right top_search middle">
                <div class="input-group">
                  <input type="text" class="form-control" placeholder="Search for...">
                  <span class="input-group-btn">
                    <button class="btn btn-default" type="button">Go!</button>
                  </span>
                </div>
              </div>
            </div>
            <div class="navbar nav_title" style="border: 0;">
                <a href="/" class="site_title"><i class="fa fa-arrows"></i>BGP Dashboard</a>
            </div>
          </ul>
        </div>
      </div>
      <!-- /top navigation -->
      <!-- page content -->
      {% block content %} {% endblock %}
      <!-- /page content -->
    </div>
  </div>

  <div id="custom_notifications" class="custom-notifications dsp_none">
    <ul class="list-unstyled notifications clearfix" data-tabbed_notifications="notif-group">
    </ul>
    <div class="clearfix"></div>
    <div id="notif-group" class="tabbed_notifications"></div>
  </div>

  <script src="/static/js/bootstrap.min.js"></script>

  <!-- gauge js -->
  <script type="text/javascript" src="/static/js/gauge/gauge.min.js"></script>
  <script type="text/javascript" src="/static/js/gauge/gauge_demo.js"></script>
  <!-- chart js -->
  <script src="/static/js/chartjs/chart.min.js"></script>
  <!-- bootstrap progress js -->
  <script src="/static/js/progressbar/bootstrap-progressbar.min.js"></script>
  <script src="/static/js/nicescroll/jquery.nicescroll.min.js"></script>
  <!-- icheck -->
  <script src="/static/js/icheck/icheck.min.js"></script>
  <!-- daterangepicker -->
  <script type="text/javascript" src="/static/js/moment.min.js"></script>
  <script type="text/javascript" src="/static/js/datepicker/daterangepicker.js"></script>

  <script src="/static/js/custom.js"></script>

  <!-- flot js -->
  <!--[if lte IE 8]><script type="text/javascript" src="/static/js/excanvas.min.js"></script><![endif]-->
  <script type="text/javascript" src="/static/js/flot/jquery.flot.js"></script>
  <script type="text/javascript" src="/static/js/flot/jquery.flot.pie.js"></script>
  <script type="text/javascript" src="/static/js/flot/jquery.flot.orderBars.js"></script>
  <script type="text/javascript" src="/static/js/flot/jquery.flot.time.min.js"></script>
  <script type="text/javascript" src="/static/js/flot/date.js"></script>
  <script type="text/javascript" src="/static/js/flot/jquery.flot.spline.js"></script>
  <script type="text/javascript" src="/static/js/flot/jquery.flot.stack.js"></script>
  <script type="text/javascript" src="/static/js/flot/curvedLines.js"></script>
  <script type="text/javascript" src="/static/js/flot/jquery.flot.resize.js"></script>
  <script>
    $(document).ready(function() {
      // [17, 74, 6, 39, 20, 85, 7]
      //[82, 23, 66, 9, 99, 6, 2]
      var data1 = [
        [gd(2012, 1, 1), 17],
        [gd(2012, 1, 2), 74],
        [gd(2012, 1, 3), 6],
        [gd(2012, 1, 4), 39],
        [gd(2012, 1, 5), 20],
        [gd(2012, 1, 6), 85],
        [gd(2012, 1, 7), 7]
      ];

      var data2 = [
        [gd(2012, 1, 1), 82],
        [gd(2012, 1, 2), 23],
        [gd(2012, 1, 3), 66],
        [gd(2012, 1, 4), 9],
        [gd(2012, 1, 5), 119],
        [gd(2012, 1, 6), 6],
        [gd(2012, 1, 7), 9]
      ];
      $("#canvas_dahs").length && $.plot($("#canvas_dahs"), [
        data1, data2
      ], {
        series: {
          lines: {
            show: false,
            fill: true
          },
          splines: {
            show: true,
            tension: 0.4,
            lineWidth: 1,
            fill: 0.4
          },
          points: {
            radius: 0,
            show: true
          },
          shadowSize: 2
        },
        grid: {
          verticalLines: true,
          hoverable: true,
          clickable: true,
          tickColor: "#d5d5d5",
          borderWidth: 1,
          color: '#fff'
        },
        colors: ["rgba(38, 185, 154, 0.38)", "rgba(3, 88, 106, 0.38)"],
        xaxis: {
          tickColor: "rgba(51, 51, 51, 0.06)",
          mode: "time",
          tickSize: [1, "day"],
          //tickLength: 10,
          axisLabel: "Date",
          axisLabelUseCanvas: true,
          axisLabelFontSizePixels: 12,
          axisLabelFontFamily: 'Verdana, Arial',
          axisLabelPadding: 10
            //mode: "time", timeformat: "%m/%d/%y", minTickSize: [1, "day"]
        },
        yaxis: {
          ticks: 8,
          tickColor: "rgba(51, 51, 51, 0.06)",
        },
        tooltip: false
      });

      function gd(year, month, day) {
        return new Date(year, month - 1, day).getTime();
      }
    });
  </script>

  <!-- worldmap -->
  <script type="text/javascript" src="/static/js/maps/jquery-jvectormap-2.0.1.min.js"></script>
  <script type="text/javascript" src="/static/js/maps/gdp-data.js"></script>
  <script type="text/javascript" src="/static/js/maps/jquery-jvectormap-world-mill-en.js"></script>
  <script type="text/javascript" src="/static/js/maps/jquery-jvectormap-us-aea-en.js"></script>
  <script>
    $(function() {
      $('#world-map-gdp').vectorMap({
        map: 'world_mill_en',
        backgroundColor: 'transparent',
        zoomOnScroll: false,
        series: {
          regions: [{
            values: gdpData,
            scale: ['#E6F2F0', '#149B7E'],
            normalizeFunction: 'polynomial'
          }]
        },
        onRegionTipShow: function(e, el, code) {
          el.html(el.html() + ' (GDP - ' + gdpData[code] + ')');
        }
      });
    });
  </script>
  <!-- skycons -->
  <script src="/static/js/skycons/skycons.js"></script>
  <script>
    var icons = new Skycons({
        "color": "#73879C"
      }),
      list = [
        "clear-day", "clear-night", "partly-cloudy-day",
        "partly-cloudy-night", "cloudy", "rain", "sleet", "snow", "wind",
        "fog"
      ],
      i;

    for (i = list.length; i--;)
      icons.set(list[i], list[i]);

    icons.play();
  </script>

  <!-- dashbord linegraph -->
  <script>
    var doughnutData = [{
      value: 30,
      color: "#455C73"
    }, {
      value: 30,
      color: "#9B59B6"
    }, {
      value: 60,
      color: "#BDC3C7"
    }, {
      value: 100,
      color: "#26B99A"
    }, {
      value: 120,
      color: "#3498DB"
    }];
    var myDoughnut = new Chart(document.getElementById("canvas1").getContext("2d")).Doughnut(doughnutData);
  </script>
  <!-- /dashbord linegraph -->
  <!-- datepicker -->
  <script type="text/javascript">
    $(document).ready(function() {

      var cb = function(start, end, label) {
        console.log(start.toISOString(), end.toISOString(), label);
        $('#reportrange span').html(start.format('MMMM D, YYYY') + ' - ' + end.format('MMMM D, YYYY'));
        //alert("Callback has fired: [" + start.format('MMMM D, YYYY') + " to " + end.format('MMMM D, YYYY') + ", label = " + label + "]");
      }

      var optionSet1 = {
        startDate: moment().subtract(29, 'days'),
        endDate: moment(),
        minDate: '01/01/2012',
        maxDate: '12/31/2015',
        dateLimit: {
          days: 60
        },
        showDropdowns: true,
        showWeekNumbers: true,
        timePicker: false,
        timePickerIncrement: 1,
        timePicker12Hour: true,
        ranges: {
          'Today': [moment(), moment()],
          'Yesterday': [moment().subtract(1, 'days'), moment().subtract(1, 'days')],
          'Last 7 Days': [moment().subtract(6, 'days'), moment()],
          'Last 30 Days': [moment().subtract(29, 'days'), moment()],
          'This Month': [moment().startOf('month'), moment().endOf('month')],
          'Last Month': [moment().subtract(1, 'month').startOf('month'), moment().subtract(1, 'month').endOf('month')]
        },
        opens: 'left',
        buttonClasses: ['btn btn-default'],
        applyClass: 'btn-small btn-primary',
        cancelClass: 'btn-small',
        format: 'MM/DD/YYYY',
        separator: ' to ',
        locale: {
          applyLabel: 'Submit',
          cancelLabel: 'Clear',
          fromLabel: 'From',
          toLabel: 'To',
          customRangeLabel: 'Custom',
          daysOfWeek: ['Su', 'Mo', 'Tu', 'We', 'Th', 'Fr', 'Sa'],
          monthNames: ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December'],
          firstDay: 1
        }
      };
      $('#reportrange span').html(moment().subtract(29, 'days').format('MMMM D, YYYY') + ' - ' + moment().format('MMMM D, YYYY'));
      $('#reportrange').daterangepicker(optionSet1, cb);
      $('#reportrange').on('show.daterangepicker', function() {
        console.log("show event fired");
      });
      $('#reportrange').on('hide.daterangepicker', function() {
        console.log("hide event fired");
      });
      $('#reportrange').on('apply.daterangepicker', function(ev, picker) {
        console.log("apply event fired, start/end dates are " + picker.startDate.format('MMMM D, YYYY') + " to " + picker.endDate.format('MMMM D, YYYY'));
      });
      $('#reportrange').on('cancel.daterangepicker', function(ev, picker) {
        console.log("cancel event fired");
      });
      $('#options1').click(function() {
        $('#reportrange').data('daterangepicker').setOptions(optionSet1, cb);
      });
      $('#options2').click(function() {
        $('#reportrange').data('daterangepicker').setOptions(optionSet2, cb);
      });
      $('#destroy').click(function() {
        $('#reportrange').data('daterangepicker').remove();
      });
    });
  </script>
  <div id="custom_notifications" class="custom-notifications dsp_none">
    <ul class="list-unstyled notifications clearfix" data-tabbed_notifications="notif-group">
    </ul>
    <div class="clearfix"></div>
    <div id="notif-group" class="tabbed_notifications"></div>
  </div>

  <!-- Datatables -->
  <script src="/static/js/datatables/js/jquery.dataTables.js"></script>
  <script src="/static/js/datatables/tools/js/dataTables.tableTools.js"></script>
  <script>
    $(document).ready(function() {
      $('input.tableflat').iCheck({
        checkboxClass: 'icheckbox_flat-green',
        radioClass: 'iradio_flat-green'
      });
    });

    var asInitVals = new Array();
    $(document).ready(function() {
      var oTable = $('#example').dataTable({
        "oLanguage": {
          "sSearch": "Search all columns:"
        },
        "aoColumnDefs": [{
            'bSortable': false,
            'aTargets': [0]
          } //disables sorting for column one
        ],
        'iDisplayLength': 12,
        "sPaginationType": "full_numbers",
        "dom": 'T<"clear">lfrtip',
        "tableTools": {
          "sSwfPath": "<?php echo base_url('static/js/Datatables/tools/swf/copy_csv_xls_pdf.swf'); ?>"
        }
      });
      $("tfoot input").keyup(function() {
        /* Filter on the column based on the index of this element's parent <th> */
        oTable.fnFilter(this.value, $("tfoot th").index($(this).parent()));
      });
      $("tfoot input").each(function(i) {
        asInitVals[i] = this.value;
      });
      $("tfoot input").focus(function() {
        if (this.className == "search_init") {
          this.className = "";
          this.value = "";
        }
      });
      $("tfoot input").blur(function(i) {
        if (this.value == "") {
          this.className = "search_init";
          this.value = asInitVals[$("tfoot input").index(this)];
        }
      });
    });
  </script>
  <script>
    NProgress.done();
  </script>
  <!-- /datepicker -->
  <!-- /footer content -->
</body>

</html>